@server = https://glorious-space-trout-vpwg7qwjx4v2pj97-8080.app.github.dev
###
GET {{server}}/api/productos/2
###
POST {{server}}/api/productos
Content-Type: application/json

{"nombre": "Leche en tarro grande", "marca": "Ideal", "cantidad": "4"}
###
GET {{server}}/api/categorias
###
POST {{server}}/api/categorias
Content-Type: application/json

{"nombre": "Lacteo"}



